/// <reference types="astro/client" />

// Runtime and binding types come from worker-configuration.d.ts, generated by
// `npm run cf-types`. Rerun it after changing wrangler.jsonc.

// Secrets are set with `wrangler secret put` and so are deliberately absent
// from wrangler.jsonc — which means the generated Env does not know about them.
// Declared here by interface merging. Optional, because a deploy can be missing
// them and the code has to cope rather than assume.
interface Env {
  /** Application Audience (AUD) tag for the run.timclaessen.com Access app. */
  ACCESS_AUD?: string;
  ICU_API_KEY?: string;
}

declare namespace App {
  interface Locals {
    /** Email from the verified Access JWT, or null when unverified. */
    accessEmail: string | null;
  }
}
